name: Keep MongoDB Atlas Alive

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch: # allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health endpoint
        run: curl -fsS https://chanu-wars-back.vercel.app/api/health
