name: Keep MongoDB Atlas Alive

on:
  schedule:
    - cron: "0 8 */4 * *" # every 4 days at 08:00 UTC
  workflow_dispatch: # allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health endpoint
        run: curl -fsS https://chanu-wars-back-niuc9xba8-lukatchanukvadzes-projects.vercel.app/api/health
